[build]
  base = "client"
  command = "npm run build"
  publish = "client/dist"

[build.environment]
  VITE_BACKEND_URL = "https://med-talk-one.vercel.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
